config/routes.rb
Rails.application.routes.draw do

  post  '/rate'              => 'rater#create', as: 'rate'
  mount RailsAdmin::Engine   => '/admin',       as: 'rails_admin'
  mount ShoppingCart::Engine => "/"

  devise_for :users, controllers: {:omniauth_callbacks => 'omniauth_callbacks'}

  root to: "main#index"

  resources :shop,     controller: 'category', only: [:index, :show]
  resources :products, controller: 'book',     only: [:index, :show]
  resources :reviews,  controller: 'review',   only: [:new, :create]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user&.admin?
      can :manage,   :all
      can :access,   :rails_admin
      can :dashboard
    elsif user&.user?
      can :read,     Book
      can :read,     Category
      can :read,     :main
      can :create,   Review,    {user: user}
    else
      can :read,     Book
      can :read,     Category
      can :read,     :main
    end
  end

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_and_belongs_to_many :books

  validates :first_name, :last_name, presence: true

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_and_belongs_to_many :authors
  has_many                :reviews,    dependent: :delete_all
  has_many                :ratings,    dependent: :delete_all
  belongs_to              :category
  
  this_is_product

  validates :title, :price, :amount, presence: true

  mount_uploader :cover, CoverUploader

  paginates_per 6

  def show_price
    return 0.0 if self.price.nil?
    (self.price.to_d/1000).round 2
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :books

  validates :title, presence: true, uniqueness: true

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :book
  belongs_to :review

  validates  :points, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 10 }

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :book
  has_one    :rating, dependent: :delete

  validates :text,  presence: true, length: { maximum: 400 }
  validates :theme, presence: true, length: { maximum: 150 }

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :reviews,          dependent: :delete_all
  has_many :ratings,          dependent: :delete_all

  this_is_user
  after_create :set_role

  def admin?
    self.has_role? :admin
  end

  def user?
    self.has_role? :user
  end

  def self.find_for_facebook_oauth(token)
    if user = User.where(email: token.info.email).first
      return user
    else
      User.create!(email: token.info.email, password: Devise.friendly_token[0,20])
    end
  end

  private

  def set_role
    self.add_role :user
  end

end

app/controllers/book_controller.rb
class BookController < ApplicationController
  load_resource

  def index
    @books = Book.all.page params[:page]
  end

  private

  def params_book
    params.require(:book).permit(:title, :price, :authors)
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  load_and_authorize_resource

  def index
    @books = Book.all.page params[:page]
    @categories = Category.all
  end

  def show
    @books = @category.books.page params[:page]
    @categories = Category.all
  end

  private

  def params_category
    params.require(:category).permit(:title)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  authorize_resource :class => false

  def index
    @book = Book.all
  end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  authorize_resource

  def new
    @book = Book.find(params[:book])
    @user = current_user
  end

  def create
    review = ReviewForm.new(params: params)
    review.apply_parameters
    review.save ? (render json: {status: 200}) : (render json: review.errors, status: :unprocessable_entity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_price(price)
    return 0.0 if price.nil?
    (price.to_d/1000).round 2
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/book/show.html.haml
.content
  .content-flex
    .book-content
      .book-title
        = @book.title
      .book-show
        .book-image
          = image_tag "#{@book.cover}"
        .part-book-card
          .book-cart-content
            .book-price
              = @book.show_price
            .book-add-cart
              = form_tag shopping_cart.add_cart_path(id: @book.id), method: 'POST' do
                = number_field_tag('quantity', 1, min: 1, max: 99, step: 1)
                = submit_tag "Add to cart", class: 'btn'
          .book-text
            = @book.description
      .review-title
        Review ---
        = link_to '- Add review to this book', new_review_path(book: @book.id)
      - @book.reviews.each do |review|
        .review-block.w100
          .review-info.review-title.row-between-center.w100(ng-controller='ratingCtrl')
            .rating(ng-init="init_book(#{review.rating&.points})")
              %star-rating(ng-model='rating.value'  readonly='rating.isReadonly' on-rating-select='rateFunction(rating)')
            .theme.w100.row-start-center
              = review.theme
            .date
              = review.created_at
          .review-user
            = "by #{review.user.first_name} #{review.user.last_name}"
          .review-text
            = review.text

app/views/category/index.html.haml
.content
  .content-flex
    .content-flex-left
      SHOP
      %ul.path
        %li Home
        %li Main
      %ul.prod.wrap-row-around-around
        - @books.each do |product|
          %li.prod-card.column-around-center
            %prod-image
              = link_to image_tag("#{product.cover}"), product_path(product)
            %prod-title
              = link_to "#{product.title}", product_path(product)
            %prod-price
              = "#{product.show_price}"
      %paginate
        = paginate @books
    .content-flex-right
      SHOP BY CATEGORIES
      %ul.categories.column-start-center.w100
        - @categories.each do |cat|
          %li.cat
            = link_to "#{cat.title}", shop_path(cat)

app/views/category/show.html.haml
= render file: 'category/index.html.haml'