config/routes.rb
Rails.application.routes.draw do

  post  '/rate'              => 'rater#create', as: 'rate'
  mount RailsAdmin::Engine   => '/admin',       as: 'rails_admin'
  mount ShoppingCart::Engine => "/"

  devise_for :users, controllers: {:omniauth_callbacks => 'omniauth_callbacks'}

  root to: "main#index"

  resources :shop,     controller: 'category', only: [:index, :show]
  resources :products, controller: 'book',     only: [:index, :show]
  resources :reviews,  controller: 'review',   only: [:new, :create]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user&.admin?
      can :manage,   :all
      can :access,   :rails_admin
      can :dashboard
    elsif user&.user?
      can :read,     Book
      can :read,     Category
      can :read,     :main
      can :create,   Review,    {user: user}
    else
      can :read,     Book
      can :read,     Category
      can :read,     :main
    end
  end

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_and_belongs_to_many :books

  validates :first_name, :last_name, presence: true

end

app/models/book.rb
class Book < ActiveRecord::Base

  has_and_belongs_to_many :authors
  has_many                :reviews,    dependent: :delete_all
  has_many                :ratings,    dependent: :delete_all
  belongs_to              :category
  
  this_is_product

  validates :title, :price, :amount, presence: true

  mount_uploader :cover, CoverUploader

  paginates_per 6

  def show_price
    return 0.0 if self.price.nil?
    (self.price.to_d/1000).round 2
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :books

  validates :title, presence: true, uniqueness: true

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :book
  belongs_to :review

  validates  :points, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 10 }

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :book
  has_one    :rating, dependent: :delete

  validates :text,  presence: true, length: { maximum: 400 }
  validates :theme, presence: true, length: { maximum: 150 }

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :reviews,          dependent: :delete_all
  has_many :ratings,          dependent: :delete_all

  this_is_user
  after_create :set_role

  def admin?
    self.has_role? :admin
  end

  def user?
    self.has_role? :user
  end

  def self.find_for_facebook_oauth(token)
    if user = User.where(email: token.info.email).first
      return user
    else
      User.create!(email: token.info.email, password: Devise.friendly_token[0,20])
    end
  end

  private

  def set_role
    self.add_role :user
  end

end

app/controllers/book_controller.rb
class BookController < ApplicationController
  load_resource

  def index
    @books = Book.all.page params[:page]
  end

  private

  def params_book
    params.require(:book).permit(:title, :price, :authors)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_price(price)
    return 0.0 if price.nil?
    (price.to_d/1000).round 2
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/layouts/application.html.haml
!!!
%html(ng-app='bookStore')
  %head
    %title= @title
    %meta(name='description' content="#{@description}")
    %meta(name='keywords' content="#{@keywords}")
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body(ng-controller='rootCtrl')
    .container
      %nav.navbar.navbar-default
        .container-fluid
          .navbar-header
            = link_to 'The Bookstore', main_app.root_path, class: 'navbar-brand'
          %div.collapse.navbar-collapse(id='bs-example-navbar-collapse-1')
            %ul.nav.navbar-nav
              %li
                = link_to 'Home',     main_app.root_path
              %li
                = link_to 'Shop',     main_app.shop_index_path
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to 'CART',     shopping_cart.cart_path
              %li
                = link_to 'Settings', shopping_cart.settings_path if current_user
              %li
                = link_to 'Orders',   shopping_cart.orders_path   if current_user
              %li
                - if current_user
                  = link_to 'Sing_out', destroy_session_path(current_user), method: 'DELETE'
                - else
                  = link_to 'Sing_in',  main_app.new_user_session_path
      .myrow
        .col-1
          .flash-messages
            = render :partial => 'layouts/partial/messages'
          = yield

app/views/layouts/partial/_messages.html.haml
- if notice
  .notice.alert-warning(role="alert")
    = notice
- if alert
  .alert.alert-danger(role="alert")
    - if alert.is_a?(Array)
      - alert.each do |message|
        = content_tag(:ul) do
          = content_tag(:li, message)
    - else
      = alert

app/views/partial/_mainform_action.html.haml
#carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  -#%ol.carousel-indicators
  -#  %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
  -#  %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
  -#  %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
  / Wrapper for slides
  .carousel-inner{:role => "listbox"}
    - @book.each do |book|
      .item(class="#{book == @book[0] ? 'active' : nil}")
        %item-content.column-start-center.w100
          %content.column-start-start.h100
            %item-title.row-start-center
              %titlebook= book.title
              %bookauthor= "&nbsp;by #{book.authors.first.first_name} #{book.authors.first.last_name}".html_safe
            %item-info.row-start-center
              %item-info-img.row-center-center
                %img-normal= image_tag book.cover.normal, class: 'w100'
              %item-info-descr.w100= book.description
            %forms
              = form_tag shopping_cart.add_cart_path(id: book.id), method: 'POST', class: 'h100' do
                %item-cart.row-start-center
                  %div= show_price(book.price)
                  %div= number_field_tag('quantity', 1, min: 1, max: 99, step: 1)
                  %div= submit_tag "Add to cart", class: 'btn'
  / Controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right
    %span.sr-only Next